Feature/themes
rarimo/docs pull request #8
Opened 2024-01-05 14:20 UTC by revomhere

2024-01-08 13:20 UTC, ardier16 requested changes

2024-01-08 13:20 UTC, ardier16 commented on docs/how-to-guides/how-to-guides.mdx
> +```
remove

2024-01-08 16:26 UTC, ardier16 commented on docs/tutorials/swapping-tokens.mdx
> +import { ChainNames } from "@rarimo/shared";
format with prettier

2024-01-08 16:26 UTC, ardier16 commented on docs/tutorials/creating-transactions.mdx
> +import { ChainNames, BridgeChain } from "@rarimo/shared";
all ts code blocks

2024-01-08 16:26 UTC, ardier16 commented on docs/reference/_category_.json
> +
remove spaces in the end of all category files
```suggestion

```

2024-01-08 16:26 UTC, ardier16 commented on docs/overview/identity.mdx
> +title: Identity Protocol
isn't it defined by h1 title already?

2024-01-08 16:26 UTC, ardier16 commented on docs/overview/bridge.mdx
> +title: Bridging Protocol
same for all other titles

2024-01-08 16:26 UTC, ardier16 commented on docs/overview/_category_.json
> +  "label": "About Rarimo",
```suggestion
  "label": "Overview",
```

2024-01-08 16:26 UTC, ardier16 commented on docs/reference/contracts/_category_.json
> +  "label": "Conracts",
```suggestion
  "label": "Contracts",
```

2024-01-08 16:26 UTC, ardier16 commented on docs/use-cases/_category_.json
> +  "label": "Overview of Use Cases",
```suggestion
  "label": "Use Cases",
```

2024-01-09 10:50 UTC, ardier16 approved these changes

2024-01-09 11:54 UTC, ihordiachenko commented on docs/overview/identity.mdx
> +sidebar_position: 2
Manually specifying the position in each document sucks. Can we list the documents in `sidebars.js` in the desired order?

2024-01-09 11:59 UTC, ihordiachenko commented
@revomhere @ardier16 we should detect the theme preference on user's device if available. Currently it's supported at least on Mac OS and Windows

2024-01-09 18:39 UTC, ihordiachenko commented
The documents are too narrow on 15" MBP. The text needs some breathing room

<img width="1678" alt="image" src="https://github.com/rarimo/docs/assets/11010444/f15c3ea8-96b7-4319-88f6-784d728ec02e">

2024-01-09 19:03 UTC, ihordiachenko requested changes

2024-01-09 19:03 UTC, ihordiachenko commented on docs/how-to-guides/validator-setup.mdx
> -  ```bash
The linter broke markdown. Please re-check the nested lists

<img width="762" alt="image" src="https://github.com/rarimo/docs/assets/11010444/754aeb89-3d01-4a06-87f5-d25a039b8a7a">

2024-01-10 10:49 UTC, ihordiachenko approved these changes

2024-01-10 10:49 UTC, merged